LABEL: 'HG002-NIST_Stanford_Illumina_6kb_matepair'
READS1 : '../test/test_1k.fq'
READS2 : ''
ALN_MAPQ_THRSD : '10'

DIR : 'refflow/'
GENOME : '/work-zfs/mschatz1/resources/refdata-GRCh38-2.1.0/fasta/genome.fa'
DIR_SECONDPASS_GENOMES : '/work-zfs/mschatz1/refflow/data/fasta'
SECONDPASS_GENOMES : ['HG002_shasta_ragoo']
# SECONDPASS_GENOMES : ['CHM13_shasta_marginpolish_helen_consensus','GM24143_shasta_marginpolish_helen_consensus','GM24149_shasta_marginpolish_helen_consensus','HG002_shasta_marginpolish_helen_consensus']


CHROM : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']

### Second-pass population genome configurations
#   selected super populations
GROUP : ['EUR', 'AMR', 'EAS', 'SAS', 'AFR']
#   filter by allele frequency [0,1]
POP_THRSD : 0
#   0: deterministic, 1: stochastic
POP_STOCHASTIC : 1
#   size of LD blocks (set to 1 to disable LD blocks)
POP_BLOCK_SIZE : 1000
#   0: update without LD, 1: update with LD
POP_USE_LD : 1

# MAPQ threshold to separate committed and deferred reads
ALN_MAPQ_THRSD : '10'

BCFTOOLS : '/home-1/cnaechy1@jhu.edu/bin/bcftools'
# LIFTOVER : '/net/langmead-bigmem-ib.bluecrab.cluster/storage/naechyun/liftover/liftover'
# PYTHON : '/home-1/cnaechy1@jhu.edu/miniconda3/bin/python3.7'
PYTHON : 'python3.7'
DIR_SCRIPTS : '/net/langmead-bigmem-ib.bluecrab.cluster/storage2/naechyun/genome_relaxation/scripts'

# TIME : '/home-1/cnaechy1@jhu.edu/bin/time-1.9'
MAX_SYSTEM_THREADS : 48
THREADS : 16
RAND_SEED : 0

MAJOR_IDX : '/net/langmead-bigmem-ib.bluecrab.cluster/storage2/naechyun/refflow/wg_hg38/major/indexes'
